# Generated by Django 3.1.12 on 2021-07-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorrecipes',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='api.recipe', verbose_name='Любимые рецепт(ы)'),
        ),
        migrations.AlterField(
            model_name='favorrecipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Картинка рецепта'),
        ),
        migrations.AlterUniqueTogether(
            name='favorrecipes',
            unique_together={('recipes', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
        migrations.RemoveField(
            model_name='favorrecipes',
            name='favorites',
        ),
    ]
