# Generated by Django 3.1.12 on 2021-07-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210716_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorrecipes',
            name='recipes',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='favorite', to='api.recipe',
                                    verbose_name='Любимые рецепты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(through='api.RecipeComponent',
                                         to='api.Ingridient',
                                         verbose_name='Ingridients'),
        ),
    ]
