# Generated by Django 3.1.12 on 2021-07-15 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210716_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='units',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingridient', to='api.ingridient', verbose_name='Компонент рецепта'),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_recipes', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
